### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by Reyesjessica** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-equipo-ija#1]
https://drive.google.com/file/d/1VD_5gxus-tpB0MhMrjiOz0mcl_lgsxUu/view?usp=drivesdk

**Comment by 22620188Oliverio** [comment]
calificacion 28 cumple con la mayoria de requerimientos solo le faltan algunas imagenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
